# Generated by Django 6.0.1 on 2026-05-17 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seatreservation'),
        ('events', '0003_dancepartner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DancePartnerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_bookings', to='events.event')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.dancepartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
