# Generated by Django 6.0.1 on 2026-05-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DancePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('style', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.FloatField(default=5.0)),
            ],
        ),
    ]
