# Generated by Django 6.0.1 on 2026-05-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('marriage', 'Marriage'), ('haldi', 'Haldi'), ('mehndi', 'Mehndi'), ('birthday', 'Birthday'), ('webinar', 'Webinar'), ('club_party', 'Club Party'), ('dj_night', 'DJ Night'), ('college_fest', 'College Fest'), ('dance_club', 'Dance Club')], max_length=20),
        ),
    ]
