# Generated by Django 6.0.1 on 2026-05-25 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('wedding', 'Wedding Hall'), ('conference', 'Conference Hall'), ('banquet', 'Banquet Hall'), ('corporate', 'Corporate Event Space'), ('community', 'Community Hall'), ('other', 'Other')], default='wedding', max_length=50)),
                ('location', models.CharField(max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HallAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='halls.hall')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='halls.hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='halls/images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='halls.hall')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['owner', '-created_at'], name='halls_hall_owner_i_449b85_idx'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['is_active', '-created_at'], name='halls_hall_is_acti_b71524_idx'),
        ),
        migrations.AddIndex(
            model_name='hallavailability',
            index=models.Index(fields=['hall', 'date'], name='halls_halla_hall_id_d53669_idx'),
        ),
        migrations.AddIndex(
            model_name='hallavailability',
            index=models.Index(fields=['hall', 'is_available', 'date'], name='halls_halla_hall_id_7a651d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hallavailability',
            unique_together={('hall', 'date')},
        ),
        migrations.AddIndex(
            model_name='hallbooking',
            index=models.Index(fields=['hall', '-created_at'], name='halls_hallb_hall_id_794d81_idx'),
        ),
        migrations.AddIndex(
            model_name='hallbooking',
            index=models.Index(fields=['user', '-created_at'], name='halls_hallb_user_id_619c83_idx'),
        ),
        migrations.AddIndex(
            model_name='hallbooking',
            index=models.Index(fields=['status'], name='halls_hallb_status_51223c_idx'),
        ),
    ]
