# Generated by Django 6.0.1 on 2026-05-27 15:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('no-response', 'No Response')], default='invited', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-event_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='hall',
            name='halls_hall_owner_i_449b85_idx',
        ),
        migrations.RemoveIndex(
            model_name='hall',
            name='halls_hall_is_acti_b71524_idx',
        ),
        migrations.RemoveIndex(
            model_name='hallavailability',
            name='halls_halla_hall_id_d53669_idx',
        ),
        migrations.RemoveIndex(
            model_name='hallavailability',
            name='halls_halla_hall_id_7a651d_idx',
        ),
        migrations.RemoveIndex(
            model_name='hallbooking',
            name='halls_hallb_hall_id_794d81_idx',
        ),
        migrations.RemoveIndex(
            model_name='hallbooking',
            name='halls_hallb_user_id_619c83_idx',
        ),
        migrations.RemoveIndex(
            model_name='hallbooking',
            name='halls_hallb_status_51223c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='hallavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hall',
            name='event_date',
            field=models.DateField(default=datetime.date(2026, 5, 27), help_text='Date of the event at this hall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='event_time',
            field=models.TimeField(default='10:00:00', help_text='Time when the event starts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='halls/'),
        ),
        migrations.AddField(
            model_name='hall',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Price per person for the event', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['owner', '-event_date'], name='halls_hall_owner_i_62022c_idx'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['is_active', '-event_date'], name='halls_hall_is_acti_078db4_idx'),
        ),
        migrations.AddField(
            model_name='hallguest',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_guests', to='halls.hall'),
        ),
        migrations.RemoveField(
            model_name='hall',
            name='price_per_day',
        ),
        migrations.AlterUniqueTogether(
            name='hallguest',
            unique_together={('hall', 'guest_email')},
        ),
    ]
