# Generated by Django 6.0.1 on 2026-06-01 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hallguest_alter_hall_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='hallguest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hallguest',
            name='hall',
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='hall',
            name='halls_hall_owner_i_62022c_idx',
        ),
        migrations.RemoveIndex(
            model_name='hall',
            name='halls_hall_is_acti_078db4_idx',
        ),
        migrations.AddField(
            model_name='hall',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='halls.venue'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['owner', '-created_at'], name='halls_hall_owner_i_449b85_idx'),
        ),
        migrations.AddIndex(
            model_name='hall',
            index=models.Index(fields=['is_active', '-created_at'], name='halls_hall_is_acti_b71524_idx'),
        ),
        migrations.DeleteModel(
            name='HallGuest',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='price_per_ticket',
        ),
    ]
