# Generated by Django 6.0.1 on 2026-06-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_hallreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallReview',
        ),
    ]
